using FoodApp.Database;
using FoodApp.Models;
using FoodApp.Services;

namespace FoodApp.Views;

public partial class EditMealPlanPage : ContentPage
{
    private readonly MealPlan _plan;
        private readonly bool _isEditingOthers;
            private readonly AppDatabase _database;
                private readonly MealPlanService _mealPlanService;
                    private readonly MeshNetworkService _networkService;

                        public EditMealPlanPage(MealPlan plan, bool isEditingOthers)
                            {
                                    InitializeComponent();
                                            
                                                    _plan = plan;
                                                            _isEditingOthers = isEditingOthers;
                                                                    
                                                                            var dbPath = Path.Combine(FileSystem.AppDataDirectory, "foodapp.db");
                                                                                    _database = new AppDatabase(dbPath);
                                                                                            _mealPlanService = new MealPlanService(_database);
                                                                                                    _networkService = new MeshNetworkService();
                                                                                                            
                                                                                                                    LoadData();
                                                                                                                        }

                                                                                                                            private async void LoadData()
                                                                                                                                {
                                                                                                                                        var user = await _database.GetUserAsync(_plan.UserId);
                                                                                                                                                UserLabel.Text = $"ویرایش جیره: {user?.Name ?? "خودم"}";
                                                                                                                                                        
                                                                                                                                                                SatBreakfast.IsChecked = _plan.SaturdayBreakfast;
                                                                                                                                                                        SatLunch.IsChecked = _plan.SaturdayLunch;
                                                                                                                                                                                SatDinner.IsChecked = _plan.SaturdayDinner;
                                                                                                                                                                                        
                                                                                                                                                                                                SunBreakfast.IsChecked = _plan.SundayBreakfast;
                                                                                                                                                                                                        SunLunch.IsChecked = _plan.SundayLunch;
                                                                                                                                                                                                                SunDinner.IsChecked = _plan.SundayDinner;
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                MonBreakfast.IsChecked = _plan.MondayBreakfast;
                                                                                                                                                                                                                                        MonLunch.IsChecked = _plan.MondayLunch;
                                                                                                                                                                                                                                                MonDinner.IsChecked = _plan.MondayDinner;
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                TueBreakfast.IsChecked = _plan.TuesdayBreakfast;
                                                                                                                                                                                                                                                                        TueLunch.IsChecked = _plan.TuesdayLunch;
                                                                                                                                                                                                                                                                                TueDinner.IsChecked = _plan.TuesdayDinner;
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                WedBreakfast.IsChecked = _plan.WednesdayBreakfast;
                                                                                                                                                                                                                                                                                                        WedLunch.IsChecked = _plan.WednesdayLunch;
                                                                                                                                                                                                                                                                                                                WedDinner.IsChecked = _plan.WednesdayDinner;
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                ThuBreakfast.IsChecked = _plan.ThursdayBreakfast;
                                                                                                                                                                                                                                                                                                                                        ThuLunch.IsChecked = _plan.ThursdayLunch;
                                                                                                                                                                                                                                                                                                                                                ThuDinner.IsChecked = _plan.ThursdayDinner;
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                FriBreakfast.IsChecked = _plan.FridayBreakfast;
                                                                                                                                                                                                                                                                                                                                                                        FriLunch.IsChecked = _plan.FridayLunch;
                                                                                                                                                                                                                                                                                                                                                                                FriDinner.IsChecked = _plan.FridayDinner;
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                        private async void OnSaveClicked(object sender, EventArgs e)
                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                    var currentUser = AuthService.GetCurrentUser();

                                                                                                                                                                                                                                                                                                                                                                                                            _plan.SaturdayBreakfast = SatBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                    _plan.SaturdayLunch = SatLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.SaturdayDinner = SatDinner.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.SundayBreakfast = SunBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    _plan.SundayLunch = SunLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.SundayDinner = SunDinner.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.MondayBreakfast = MonBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _plan.MondayLunch = MonLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.MondayDinner = MonDinner.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.TuesdayBreakfast = TueBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _plan.TuesdayLunch = TueLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.TuesdayDinner = TueDinner.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.WednesdayBreakfast = WedBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _plan.WednesdayLunch = WedLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.WednesdayDinner = WedDinner.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.ThursdayBreakfast = ThuBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _plan.ThursdayLunch = ThuLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.ThursdayDinner = ThuDinner.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.FridayBreakfast = FriBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _plan.FridayLunch = FriLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _plan.FridayDinner = FriDinner.IsChecked;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await _mealPlanService.UpdateMealPlanAsync(_plan, currentUser.Name);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await _networkService.BroadcastMealPlanAsync(_plan);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await DisplayAlert("موفق", "جیره ذخیره شد", "باشه");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await Navigation.PopAsync();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }