using FoodApp.Database;
using FoodApp.Models;
using FoodApp.Services;

namespace FoodApp.Views.User;

public partial class UserMainPage : ContentPage
{
    private readonly AppDatabase _database;
        private readonly MealPlanService _mealPlanService;
            private readonly MeshNetworkService _networkService;
                private MealPlan _currentPlan;

                    public UserMainPage()
                        {
                                InitializeComponent();
                                        
                                                var dbPath = Path.Combine(FileSystem.AppDataDirectory, "foodapp.db");
                                                        _database = new AppDatabase(dbPath);
                                                                _mealPlanService = new MealPlanService(_database);
                                                                        _networkService = new MeshNetworkService();
                                                                                
                                                                                        SetupWeekPicker();
                                                                                                YearEntry.Text = DateTime.Now.Year.ToString();
                                                                                                        
                                                                                                                var user = AuthService.GetCurrentUser();
                                                                                                                        WelcomeLabel.Text = $"خوش آمدید، {user?.Name}";
                                                                                                                                
                                                                                                                                        _ = _networkService.StartAsync();
                                                                                                                                            }

                                                                                                                                                private void SetupWeekPicker()
                                                                                                                                                    {
                                                                                                                                                            for (int i = 1; i <= 52; i++)
                                                                                                                                                                    {
                                                                                                                                                                                WeekPicker.Items.Add($"هفته {i}");
                                                                                                                                                                                        }
                                                                                                                                                                                                
                                                                                                                                                                                                        var currentWeek = System.Globalization.CultureInfo.CurrentCulture.Calendar.GetWeekOfYear(
                                                                                                                                                                                                                    DateTime.Now, 
                                                                                                                                                                                                                                System.Globalization.CalendarWeekRule.FirstFourDayWeek, 
                                                                                                                                                                                                                                            DayOfWeek.Saturday);
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                            WeekPicker.SelectedIndex = currentWeek - 1;
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                    private async void OnLoadClicked(object sender, EventArgs e)
                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                var user = AuthService.GetCurrentUser();
                                                                                                                                                                                                                                                                                        var week = WeekPicker.SelectedIndex + 1;
                                                                                                                                                                                                                                                                                                var year = int.Parse(YearEntry.Text);

                                                                                                                                                                                                                                                                                                        _currentPlan = await _mealPlanService.GetOrCreateMealPlanAsync(user.Id, week, year);
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                        SatBreakfast.IsChecked = _currentPlan.SaturdayBreakfast;
                                                                                                                                                                                                                                                                                                                                SatLunch.IsChecked = _currentPlan.SaturdayLunch;
                                                                                                                                                                                                                                                                                                                                        SatDinner.IsChecked = _currentPlan.SaturdayDinner;
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                        SunBreakfast.IsChecked = _currentPlan.SundayBreakfast;
                                                                                                                                                                                                                                                                                                                                                                SunLunch.IsChecked = _currentPlan.SundayLunch;
                                                                                                                                                                                                                                                                                                                                                                        SunDinner.IsChecked = _currentPlan.SundayDinner;
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                        MonBreakfast.IsChecked = _currentPlan.MondayBreakfast;
                                                                                                                                                                                                                                                                                                                                                                                                MonLunch.IsChecked = _currentPlan.MondayLunch;
                                                                                                                                                                                                                                                                                                                                                                                                        MonDinner.IsChecked = _currentPlan.MondayDinner;
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                        TueBreakfast.IsChecked = _currentPlan.TuesdayBreakfast;
                                                                                                                                                                                                                                                                                                                                                                                                                                TueLunch.IsChecked = _currentPlan.TuesdayLunch;
                                                                                                                                                                                                                                                                                                                                                                                                                                        TueDinner.IsChecked = _currentPlan.TuesdayDinner;
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                        WedBreakfast.IsChecked = _currentPlan.WednesdayBreakfast;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                WedLunch.IsChecked = _currentPlan.WednesdayLunch;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        WedDinner.IsChecked = _currentPlan.WednesdayDinner;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ThuBreakfast.IsChecked = _currentPlan.ThursdayBreakfast;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ThuLunch.IsChecked = _currentPlan.ThursdayLunch;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ThuDinner.IsChecked = _currentPlan.ThursdayDinner;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FriBreakfast.IsChecked = _currentPlan.FridayBreakfast;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FriLunch.IsChecked = _currentPlan.FridayLunch;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FriDinner.IsChecked = _currentPlan.FridayDinner;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        StatusLabel.Text = "جیره بارگذاری شد";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                private async void OnSaveClicked(object sender, EventArgs e)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (_currentPlan == null) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var user = AuthService.GetCurrentUser();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.SaturdayBreakfast = SatBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _currentPlan.SaturdayLunch = SatLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.SaturdayDinner = SatDinner.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.SundayBreakfast = SunBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _currentPlan.SundayLunch = SunLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.SundayDinner = SunDinner.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.MondayBreakfast = MonBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _currentPlan.MondayLunch = MonLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.MondayDinner = MonDinner.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.TuesdayBreakfast = TueBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _currentPlan.TuesdayLunch = TueLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.TuesdayDinner = TueDinner.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.WednesdayBreakfast = WedBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _currentPlan.WednesdayLunch = WedLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.WednesdayDinner = WedDinner.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.ThursdayBreakfast = ThuBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _currentPlan.ThursdayLunch = ThuLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.ThursdayDinner = ThuDinner.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.FridayBreakfast = FriBreakfast.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _currentPlan.FridayLunch = FriLunch.IsChecked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _currentPlan.FridayDinner = FriDinner.IsChecked;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await _mealPlanService.UpdateMealPlanAsync(_currentPlan, user.Name);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await _networkService.BroadcastMealPlanAsync(_currentPlan);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    StatusLabel.Text = "جیره ذخیره و همگام‌سازی شد";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private async void OnGoToChatClicked(object sender, EventArgs e)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await Navigation.PushAsync(new Views.Chat.ChatPage());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }