using FoodApp.Database;
using FoodApp.Models;
using FoodApp.Services;

namespace FoodApp.Views.Manager;

public partial class ManagerMainPage : ContentPage
{
    private readonly AppDatabase _database;
        private readonly MealPlanService _mealPlanService;
            private readonly MeshNetworkService _networkService;

                public ManagerMainPage()
                    {
                            InitializeComponent();
                                    
                                            var dbPath = Path.Combine(FileSystem.AppDataDirectory, "foodapp.db");
                                                    _database = new AppDatabase(dbPath);
                                                            _mealPlanService = new MealPlanService(_database);
                                                                    _networkService = new MeshNetworkService();
                                                                            
                                                                                    SetupWeekPicker();
                                                                                            YearEntry.Text = DateTime.Now.Year.ToString();
                                                                                                    
                                                                                                            var user = AuthService.GetCurrentUser();
                                                                                                                    WelcomeLabel.Text = $"مدیر: {user?.Name}";
                                                                                                                            
                                                                                                                                    _ = _networkService.StartAsync();
                                                                                                                                            _networkService.MealPlanReceived += OnMealPlanReceivedFromNetwork;
                                                                                                                                                }

                                                                                                                                                    private void SetupWeekPicker()
                                                                                                                                                        {
                                                                                                                                                                for (int i = 1; i <= 52; i++)
                                                                                                                                                                            WeekPicker.Items.Add($"هفته {i}");
                                                                                                                                                                                    
                                                                                                                                                                                            var currentWeek = System.Globalization.CultureInfo.CurrentCulture.Calendar.GetWeekOfYear(
                                                                                                                                                                                                        DateTime.Now, 
                                                                                                                                                                                                                    System.Globalization.CalendarWeekRule.FirstFourDayWeek, 
                                                                                                                                                                                                                                DayOfWeek.Saturday);
                                                                                                                                                                                                                                        WeekPicker.SelectedIndex = currentWeek - 1;
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                private async void OnShowAllClicked(object sender, EventArgs e)
                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                            await LoadMealPlansAsync();
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                    private async Task LoadMealPlansAsync()
                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                var week = WeekPicker.SelectedIndex + 1;
                                                                                                                                                                                                                                                                                        var year = int.Parse(YearEntry.Text);
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                        var plans = await _mealPlanService.GetAllMealPlansForWeekAsync(week, year);
                                                                                                                                                                                                                                                                                                                var users = await _database.GetUsersAsync();
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                var displayList = new List<MealPlanDisplay>();
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                foreach (var plan in plans)
                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                    var user = users.FirstOrDefault(u => u.Id == plan.UserId);
                                                                                                                                                                                                                                                                                                                                                                                displayList.Add(new MealPlanDisplay
                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                            PlanId = plan.Id,
                                                                                                                                                                                                                                                                                                                                                                                                                            UserId = plan.UserId,
                                                                                                                                                                                                                                                                                                                                                                                                                                            UserName = user?.Name ?? "نامشخص",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            MealSummary = GetMealSummary(plan),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            LastModified = plan.LastModified,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            OriginalPlan = plan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                MealPlansCollection.ItemsSource = displayList;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        private string GetMealSummary(MealPlan plan)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int count = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (plan.SaturdayBreakfast || plan.SaturdayLunch || plan.SaturdayDinner) count++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (plan.SundayBreakfast || plan.SundayLunch || plan.SundayDinner) count++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (plan.MondayBreakfast || plan.MondayLunch || plan.MondayDinner) count++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (plan.TuesdayBreakfast || plan.TuesdayLunch || plan.TuesdayDinner) count++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (plan.WednesdayBreakfast || plan.WednesdayLunch || plan.WednesdayDinner) count++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (plan.ThursdayBreakfast || plan.ThursdayLunch || plan.ThursdayDinner) count++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (plan.FridayBreakfast || plan.FridayLunch || plan.FridayDinner) count++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return $"{count} روز فعال";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    private async void OnEditPlanClicked(object sender, EventArgs e)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var button = sender as Button;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var display = button?.CommandParameter as MealPlanDisplay;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (display != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await Navigation.PushAsync(new EditMealPlanPage(display.OriginalPlan, true));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private async void OnEditMyPlanClicked(object sender, EventArgs e)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var user = AuthService.GetCurrentUser();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var week = WeekPicker.SelectedIndex + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var year = int.Parse(YearEntry.Text);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var plan = await _mealPlanService.GetOrCreateMealPlanAsync(user.Id, week, year);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await Navigation.PushAsync(new EditMealPlanPage(plan, false));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        private async void OnMealPlanReceivedFromNetwork(object sender, MealPlan plan)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var existing = await _database.GetMealPlanAsync(plan.UserId, plan.WeekNumber, plan.Year);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (existing == null || existing.Version < plan.Version)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (existing == null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await _database.SaveMealPlanAsync(plan);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await _database.UpdateMealPlanAsync(plan);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await MainThread.InvokeOnMainThreadAsync(async () => await LoadMealPlansAsync());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public class MealPlanDisplay
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public string PlanId { get; set; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public string UserId { get; set; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public string UserName { get; set; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public string MealSummary { get; set; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public DateTime LastModified { get; set; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public MealPlan OriginalPlan { get; set; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }